### ISSUE TITLE
(Ajax OR jquery Object) XOR (only Ajax)

### ISSUE THREAD

**Issue by jasonjan2003** [badgerherald/hrld-showcase#3]
Should we remove the ability to retrieve img urls directly from img dom elements, or should there be two separate modes for showcase so it can take in either objects and find img links or array of links to make a gallery?

**Comment by mjneil** [comment]
What I decided on was basically jquery goes through dom and collects all the attachment ids, then sends a post request to the ajax function defined in the wordpress plugin, which will return an array of objects with all the attachment sources and meta data such as title caption etc. There is also a filter hook within the ajax function so that other plugins or themes can edit the response before it gets sent back. This is mainly so we can filter in media credit from the media credit plugin.
